# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 14pt \"Felix Titling\";\n"
"      border: 2px solid gray;\n"
"      border-radius: 10px;\n"
"     padding: 0 8px;\n"
"      background: yellow;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   background-color:white;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"   background-color:blue;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{\n"
"   background-color:pink;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listenButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listenButton.sizePolicy().hasHeightForWidth())
        self.listenButton.setSizePolicy(sizePolicy)
        self.listenButton.setCheckable(True)
        self.listenButton.setChecked(False)
        self.listenButton.setObjectName("listenButton")
        self.verticalLayout_2.addWidget(self.listenButton)
        self.processButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processButton.sizePolicy().hasHeightForWidth())
        self.processButton.setSizePolicy(sizePolicy)
        self.processButton.setCheckable(True)
        self.processButton.setChecked(False)
        self.processButton.setObjectName("processButton")
        self.verticalLayout_2.addWidget(self.processButton)
        self.configButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configButton.sizePolicy().hasHeightForWidth())
        self.configButton.setSizePolicy(sizePolicy)
        self.configButton.setObjectName("configButton")
        self.verticalLayout_2.addWidget(self.configButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 9, -1)
        self.horizontalLayout_2.setSpacing(27)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftNut = QtWidgets.QPushButton(parent=self.frame)
        self.leftNut.setObjectName("leftNut")
        self.horizontalLayout_2.addWidget(self.leftNut)
        self.rightNut = QtWidgets.QPushButton(parent=self.frame)
        self.rightNut.setObjectName("rightNut")
        self.horizontalLayout_2.addWidget(self.rightNut)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.processButton.clicked.connect(MainWindow.showNormal) # type: ignore
        self.listenButton.clicked.connect(MainWindow.showFullScreen) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listenButton.setText(_translate("MainWindow", "LISTEN"))
        self.processButton.setText(_translate("MainWindow", "PROCESS"))
        self.processButton.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.configButton.setText(_translate("MainWindow", "CONFIG"))
        self.configButton.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.leftNut.setText(_translate("MainWindow", "left nut"))
        self.rightNut.setText(_translate("MainWindow", "right nut"))
