# Form implementation generated from reading ui file 'AddWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 480)
        Form.setStyleSheet("QLabel#label_title, #label_subtitle{ \n"
"    \n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    color:rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    background:rgb(255, 85, 0);\n"
"    border: 2px solid gray;\n"
"      border-radius: 10px;\n"
"     padding: 0 8px;\n"
"}\n"
"\n"
"QPushButton#button_addSpeaker, QPushButton#button_addEvent, QPushButton#button_toggle_widget{\n"
"    font: 63 20pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255, 140, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 63 16pt \"Bahnschrift SemiBold\";\n"
"}    \n"
"\n"
"QLabel{\n"
"    \n"
"    font: 63 12pt \"Bahnschrift SemiBold\";\n"
"}\n"
"")
        self.button_toggle_widget = QtWidgets.QPushButton(parent=Form)
        self.button_toggle_widget.setEnabled(True)
        self.button_toggle_widget.setGeometry(QtCore.QRect(320, 10, 221, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_toggle_widget.sizePolicy().hasHeightForWidth())
        self.button_toggle_widget.setSizePolicy(sizePolicy)
        self.button_toggle_widget.setFlat(False)
        self.button_toggle_widget.setObjectName("button_toggle_widget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 64, 560, 415))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_addSpeaker = QtWidgets.QWidget()
        self.page_addSpeaker.setObjectName("page_addSpeaker")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_addSpeaker)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_speakerList = QtWidgets.QLabel(parent=self.page_addSpeaker)
        self.label_speakerList.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_speakerList.setObjectName("label_speakerList")
        self.verticalLayout.addWidget(self.label_speakerList)
        self.table_speakers = QtWidgets.QTableWidget(parent=self.page_addSpeaker)
        self.table_speakers.setShowGrid(True)
        self.table_speakers.setColumnCount(3)
        self.table_speakers.setObjectName("table_speakers")
        self.table_speakers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_speakers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_speakers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_speakers.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.table_speakers)
        self.line = QtWidgets.QFrame(parent=self.page_addSpeaker)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_addSpeaker = QtWidgets.QLabel(parent=self.page_addSpeaker)
        self.label_addSpeaker.setObjectName("label_addSpeaker")
        self.verticalLayout.addWidget(self.label_addSpeaker)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(parent=self.page_addSpeaker)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_name)
        self.line_name = QtWidgets.QLineEdit(parent=self.page_addSpeaker)
        self.line_name.setObjectName("line_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_name)
        self.label_code = QtWidgets.QLabel(parent=self.page_addSpeaker)
        self.label_code.setObjectName("label_code")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_code)
        self.line_code = QtWidgets.QLineEdit(parent=self.page_addSpeaker)
        self.line_code.setObjectName("line_code")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_code)
        self.verticalLayout.addLayout(self.formLayout)
        self.button_addSpeaker = QtWidgets.QPushButton(parent=self.page_addSpeaker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_addSpeaker.sizePolicy().hasHeightForWidth())
        self.button_addSpeaker.setSizePolicy(sizePolicy)
        self.button_addSpeaker.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.button_addSpeaker.setObjectName("button_addSpeaker")
        self.verticalLayout.addWidget(self.button_addSpeaker)
        self.stackedWidget.addWidget(self.page_addSpeaker)
        self.page_addEvent = QtWidgets.QWidget()
        self.page_addEvent.setObjectName("page_addEvent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_addEvent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_eventList = QtWidgets.QLabel(parent=self.page_addEvent)
        self.label_eventList.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_eventList.setObjectName("label_eventList")
        self.verticalLayout_2.addWidget(self.label_eventList)
        self.table_events = QtWidgets.QTableWidget(parent=self.page_addEvent)
        self.table_events.setObjectName("table_events")
        self.table_events.setColumnCount(3)
        self.table_events.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_events.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_events.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_events.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.table_events)
        self.line_2 = QtWidgets.QFrame(parent=self.page_addEvent)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_addEvent = QtWidgets.QLabel(parent=self.page_addEvent)
        self.label_addEvent.setObjectName("label_addEvent")
        self.verticalLayout_2.addWidget(self.label_addEvent)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_eventTitle = QtWidgets.QLabel(parent=self.page_addEvent)
        self.label_eventTitle.setObjectName("label_eventTitle")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_eventTitle)
        self.label_2 = QtWidgets.QLabel(parent=self.page_addEvent)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.line_title = QtWidgets.QLineEdit(parent=self.page_addEvent)
        self.line_title.setObjectName("line_title")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_title)
        self.line_date = QtWidgets.QLineEdit(parent=self.page_addEvent)
        self.line_date.setObjectName("line_date")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_date)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.button_addEvent = QtWidgets.QPushButton(parent=self.page_addEvent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_addEvent.sizePolicy().hasHeightForWidth())
        self.button_addEvent.setSizePolicy(sizePolicy)
        self.button_addEvent.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.button_addEvent.setDefault(False)
        self.button_addEvent.setObjectName("button_addEvent")
        self.verticalLayout_2.addWidget(self.button_addEvent)
        self.stackedWidget.addWidget(self.page_addEvent)
        self.button_back = QtWidgets.QPushButton(parent=Form)
        self.button_back.setEnabled(True)
        self.button_back.setGeometry(QtCore.QRect(20, 10, 221, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_back.sizePolicy().hasHeightForWidth())
        self.button_back.setSizePolicy(sizePolicy)
        self.button_back.setFlat(False)
        self.button_back.setObjectName("button_back")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_toggle_widget.setText(_translate("Form", "To Event List"))
        self.label_speakerList.setText(_translate("Form", "Speaker List"))
        item = self.table_speakers.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table_speakers.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.table_speakers.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Code"))
        self.label_addSpeaker.setText(_translate("Form", "Add New Speaker"))
        self.label_name.setText(_translate("Form", "Name"))
        self.label_code.setText(_translate("Form", "Code"))
        self.button_addSpeaker.setText(_translate("Form", "Add Speaker"))
        self.label_eventList.setText(_translate("Form", "Event List"))
        item = self.table_events.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table_events.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Title"))
        item = self.table_events.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date"))
        self.label_addEvent.setText(_translate("Form", "Add New Event"))
        self.label_eventTitle.setText(_translate("Form", "Title"))
        self.label_2.setText(_translate("Form", "Date"))
        self.button_addEvent.setText(_translate("Form", "Add event"))
        self.button_back.setText(_translate("Form", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
