# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 415)
        Form.setStyleSheet("QLabel#label_title{ \n"
"    font: 24pt \"Old English Text MT\";\n"
"    color:rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    background:rgb(255, 85, 0);\n"
"    border: 2px solid gray;\n"
"      border-radius: 10px;\n"
"     padding: 0 8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background:rgb(255, 140, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 63 16pt \"Bahnschrift SemiBold\";\n"
"}    \n"
"")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(9, 90, 536, 321))
        self.frame.setStyleSheet("QLabel#label_title, #label_subtitle{ \n"
"font: 24pt \"Old English Text MT\";\n"
"    color:rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    background:rgb(255, 85, 0);\n"
"    border: 2px solid gray;\n"
"      border-radius: 10px;\n"
"     padding: 0 8px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background:rgb(255, 140, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 63 16pt \"Bahnschrift SemiBold\";\n"
"}    \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout_buttons = QtWidgets.QVBoxLayout()
        self.layout_buttons.setObjectName("layout_buttons")
        self.button_listen = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_listen.sizePolicy().hasHeightForWidth())
        self.button_listen.setSizePolicy(sizePolicy)
        self.button_listen.setObjectName("button_listen")
        self.layout_buttons.addWidget(self.button_listen)
        self.button_process = QtWidgets.QPushButton(parent=self.frame)
        self.button_process.setObjectName("button_process")
        self.layout_buttons.addWidget(self.button_process)
        self.button_create = QtWidgets.QPushButton(parent=self.frame)
        self.button_create.setObjectName("button_create")
        self.layout_buttons.addWidget(self.button_create)
        self.horizontalLayout.addLayout(self.layout_buttons)
        self.layout_labels = QtWidgets.QVBoxLayout()
        self.layout_labels.setObjectName("layout_labels")
        self.label_listen = QtWidgets.QLabel(parent=self.frame)
        self.label_listen.setObjectName("label_listen")
        self.layout_labels.addWidget(self.label_listen)
        self.label_process = QtWidgets.QLabel(parent=self.frame)
        self.label_process.setObjectName("label_process")
        self.layout_labels.addWidget(self.label_process)
        self.label_add = QtWidgets.QLabel(parent=self.frame)
        self.label_add.setObjectName("label_add")
        self.layout_labels.addWidget(self.label_add)
        self.horizontalLayout.addLayout(self.layout_labels)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(1, 8)
        self.label_icon = QtWidgets.QLabel(parent=Form)
        self.label_icon.setGeometry(QtCore.QRect(220, 0, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon.sizePolicy().hasHeightForWidth())
        self.label_icon.setSizePolicy(sizePolicy)
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap("asset/images/Solaire.png"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setObjectName("label_icon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "Audivi, scripsi, comperi."))
        self.button_listen.setText(_translate("Form", "Listen"))
        self.button_process.setText(_translate("Form", "Process"))
        self.button_create.setText(_translate("Form", "Add New"))
        self.label_listen.setText(_translate("Form", "Start recording some stuff"))
        self.label_process.setText(_translate("Form", "Process an existing event\'s transcript."))
        self.label_add.setText(_translate("Form", "Add new event or speaker."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
