# Form implementation generated from reading ui file 'ui/ProcessWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 412)
        Form.setStyleSheet("QLabel#label_title, #label_subtitle{ \n"
"    \n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    color:rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    background:rgb(255, 85, 0);\n"
"    border: 2px solid gray;\n"
"      border-radius: 10px;\n"
"     padding: 0 8px;\n"
"}\n"
"\n"
"QPushButton#button_addSpeaker, QPushButton#button_addEvent, QPushButton#button_toggle_widget{\n"
"    font: 63 20pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255, 140, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 63 16pt \"Bahnschrift SemiBold\";\n"
"}    \n"
"\n"
"QLabel{\n"
"    \n"
"    font: 63 12pt \"Bahnschrift SemiBold\";\n"
"}\n"
"")
        self.button_back = QtWidgets.QPushButton(parent=Form)
        self.button_back.setGeometry(QtCore.QRect(40, 20, 101, 51))
        self.button_back.setObjectName("button_back")
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 90, 441, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_chooseEvent = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_chooseEvent.setObjectName("label_chooseEvent")
        self.verticalLayout.addWidget(self.label_chooseEvent)
        self.combo_eventList = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.combo_eventList.setObjectName("combo_eventList")
        self.verticalLayout.addWidget(self.combo_eventList)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setGeometry(QtCore.QRect(40, 150, 441, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=Form)
        self.line_2.setGeometry(QtCore.QRect(480, 10, 20, 391))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.table_recordData = QtWidgets.QTableWidget(parent=Form)
        self.table_recordData.setGeometry(QtCore.QRect(500, 10, 671, 391))
        self.table_recordData.setObjectName("table_recordData")
        self.table_recordData.setColumnCount(5)
        self.table_recordData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(4, item)
        self.label_theme = QtWidgets.QLabel(parent=Form)
        self.label_theme.setGeometry(QtCore.QRect(40, 170, 441, 21))
        self.label_theme.setObjectName("label_theme")
        self.label_date = QtWidgets.QLabel(parent=Form)
        self.label_date.setGeometry(QtCore.QRect(40, 200, 441, 21))
        self.label_date.setObjectName("label_date")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 270, 181, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 270, 181, 61))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_back.setText(_translate("Form", "Back"))
        self.label_chooseEvent.setText(_translate("Form", "Choose Event"))
        item = self.table_recordData.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table_recordData.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Question"))
        item = self.table_recordData.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Speaker"))
        item = self.table_recordData.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Audio Transcript"))
        item = self.table_recordData.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Text Transcript"))
        self.label_theme.setText(_translate("Form", "Theme Here"))
        self.label_date.setText(_translate("Form", "Date Here"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
