# Form implementation generated from reading ui file 'ui/ProcessWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1636, 707)
        Form.setStyleSheet("QLabel#label_title, #label_subtitle{ \n"
"    \n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    color:rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 63 28pt \"Bahnschrift SemiBold SemiConden\";\n"
"    background:rgb(255, 85, 0);\n"
"    border: 2px solid gray;\n"
"      border-radius: 10px;\n"
"     padding: 0 8px;\n"
"}\n"
"\n"
"QPushButton#button_addSpeaker, QPushButton#button_addEvent, QPushButton#button_toggle_widget{\n"
"    font: 63 20pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(255, 140, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    background: rgb(150, 150, 150);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 63 16pt \"Bahnschrift SemiBold\";\n"
"}    \n"
"\n"
"QLabel{\n"
"    \n"
"    font: 63 12pt \"Bahnschrift SemiBold\";\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font: 63 12pt \"Bahnschrift SemiBold\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    font: 14pt \"Bahnschrift\";\n"
"}\n"
"\n"
"QHeaderView{\n"
"    font: 63 18pt \"Bahnschrift SemiBold SemiConden\";\n"
"}\n"
"\n"
"QLabel#label_NerdMode{\n"
"    font: 63 20pt \"Bahnschrift SemiBold\";\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font: 63 12pt \"Bahnschrift SemiBold\";\n"
"}")
        self.button_back = QtWidgets.QPushButton(parent=Form)
        self.button_back.setGeometry(QtCore.QRect(40, 20, 101, 51))
        self.button_back.setObjectName("button_back")
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 90, 441, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_chooseEvent = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_chooseEvent.setObjectName("label_chooseEvent")
        self.verticalLayout.addWidget(self.label_chooseEvent)
        self.combo_eventList = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.combo_eventList.setObjectName("combo_eventList")
        self.verticalLayout.addWidget(self.combo_eventList)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setGeometry(QtCore.QRect(40, 150, 441, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=Form)
        self.line_2.setGeometry(QtCore.QRect(480, 10, 20, 661))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.table_recordData = QtWidgets.QTableWidget(parent=Form)
        self.table_recordData.setGeometry(QtCore.QRect(500, 10, 1121, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_recordData.sizePolicy().hasHeightForWidth())
        self.table_recordData.setSizePolicy(sizePolicy)
        self.table_recordData.setObjectName("table_recordData")
        self.table_recordData.setColumnCount(6)
        self.table_recordData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_recordData.setHorizontalHeaderItem(5, item)
        self.label_theme = QtWidgets.QLabel(parent=Form)
        self.label_theme.setGeometry(QtCore.QRect(40, 170, 441, 21))
        self.label_theme.setObjectName("label_theme")
        self.label_date = QtWidgets.QLabel(parent=Form)
        self.label_date.setGeometry(QtCore.QRect(40, 200, 441, 21))
        self.label_date.setObjectName("label_date")
        self.button_process = QtWidgets.QPushButton(parent=Form)
        self.button_process.setGeometry(QtCore.QRect(40, 330, 161, 61))
        self.button_process.setObjectName("button_process")
        self.line_3 = QtWidgets.QFrame(parent=Form)
        self.line_3.setGeometry(QtCore.QRect(250, 230, 16, 171))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.check_isSplit = QtWidgets.QCheckBox(parent=Form)
        self.check_isSplit.setGeometry(QtCore.QRect(40, 240, 181, 21))
        self.check_isSplit.setObjectName("check_isSplit")
        self.check_saveResult = QtWidgets.QCheckBox(parent=Form)
        self.check_saveResult.setGeometry(QtCore.QRect(40, 270, 181, 21))
        self.check_saveResult.setObjectName("check_saveResult")
        self.check_nerdMode = QtWidgets.QCheckBox(parent=Form)
        self.check_nerdMode.setEnabled(True)
        self.check_nerdMode.setGeometry(QtCore.QRect(40, 300, 181, 21))
        self.check_nerdMode.setObjectName("check_nerdMode")
        self.button_transcribe_all = QtWidgets.QPushButton(parent=Form)
        self.button_transcribe_all.setGeometry(QtCore.QRect(290, 330, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.button_transcribe_all.setFont(font)
        self.button_transcribe_all.setStyleSheet("font: 63 20pt \"Bahnschrift SemiBold\";")
        self.button_transcribe_all.setObjectName("button_transcribe_all")
        self.check_saveTranscriptToCSV = QtWidgets.QCheckBox(parent=Form)
        self.check_saveTranscriptToCSV.setGeometry(QtCore.QRect(280, 300, 191, 21))
        self.check_saveTranscriptToCSV.setObjectName("check_saveTranscriptToCSV")
        self.check_saveTranscriptToDatabase = QtWidgets.QCheckBox(parent=Form)
        self.check_saveTranscriptToDatabase.setGeometry(QtCore.QRect(280, 270, 191, 21))
        self.check_saveTranscriptToDatabase.setObjectName("check_saveTranscriptToDatabase")
        self.label_NerdMode = QtWidgets.QLabel(parent=Form)
        self.label_NerdMode.setGeometry(QtCore.QRect(50, 410, 431, 41))
        self.label_NerdMode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_NerdMode.setObjectName("label_NerdMode")
        self.line_4 = QtWidgets.QFrame(parent=Form)
        self.line_4.setGeometry(QtCore.QRect(37, 440, 441, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_FeatureExtraction = QtWidgets.QLabel(parent=Form)
        self.label_FeatureExtraction.setGeometry(QtCore.QRect(40, 460, 141, 21))
        self.label_FeatureExtraction.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_FeatureExtraction.setObjectName("label_FeatureExtraction")
        self.label_Method = QtWidgets.QLabel(parent=Form)
        self.label_Method.setGeometry(QtCore.QRect(50, 570, 131, 21))
        self.label_Method.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_Method.setObjectName("label_Method")
        self.check_isWeighted = QtWidgets.QCheckBox(parent=Form)
        self.check_isWeighted.setGeometry(QtCore.QRect(40, 530, 131, 21))
        self.check_isWeighted.setObjectName("check_isWeighted")
        self.line_nTopics = QtWidgets.QLineEdit(parent=Form)
        self.line_nTopics.setGeometry(QtCore.QRect(320, 500, 41, 20))
        self.line_nTopics.setObjectName("line_nTopics")
        self.line_epsilon = QtWidgets.QLineEdit(parent=Form)
        self.line_epsilon.setGeometry(QtCore.QRect(340, 580, 41, 20))
        self.line_epsilon.setObjectName("line_epsilon")
        self.line_minSamp = QtWidgets.QLineEdit(parent=Form)
        self.line_minSamp.setGeometry(QtCore.QRect(410, 580, 41, 20))
        self.line_minSamp.setObjectName("line_minSamp")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(370, 500, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(390, 580, 21, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(460, 580, 31, 21))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 450, 121, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radio_Embed = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.radio_Embed.setObjectName("radio_Embed")
        self.verticalLayout_2.addWidget(self.radio_Embed)
        self.radio_LDA = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.radio_LDA.setObjectName("radio_LDA")
        self.verticalLayout_2.addWidget(self.radio_LDA)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 570, 141, 83))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radio_DBSCAN = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.radio_DBSCAN.setObjectName("radio_DBSCAN")
        self.verticalLayout_4.addWidget(self.radio_DBSCAN)
        self.radio_LOF = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.radio_LOF.setObjectName("radio_LOF")
        self.verticalLayout_4.addWidget(self.radio_LOF)
        self.radio_IF = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.radio_IF.setObjectName("radio_IF")
        self.verticalLayout_4.addWidget(self.radio_IF)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_back.setText(_translate("Form", "Back"))
        self.label_chooseEvent.setText(_translate("Form", "Choose Event"))
        item = self.table_recordData.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table_recordData.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Question"))
        item = self.table_recordData.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Speaker"))
        item = self.table_recordData.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Audio"))
        item = self.table_recordData.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Text Transcript"))
        item = self.table_recordData.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Lang"))
        self.label_theme.setText(_translate("Form", "Theme Here"))
        self.label_date.setText(_translate("Form", "Date Here"))
        self.button_process.setText(_translate("Form", "Process"))
        self.check_isSplit.setText(_translate("Form", "Split Into Sentences"))
        self.check_saveResult.setText(_translate("Form", "Save Cluster Result"))
        self.check_nerdMode.setText(_translate("Form", "Nerd Mode🤓 (TBA)"))
        self.button_transcribe_all.setText(_translate("Form", "Transcribe"))
        self.check_saveTranscriptToCSV.setText(_translate("Form", "Save Transcript to CSV"))
        self.check_saveTranscriptToDatabase.setText(_translate("Form", "Save Transcript to DB"))
        self.label_NerdMode.setText(_translate("Form", "Nerd Corner 🤓"))
        self.label_FeatureExtraction.setText(_translate("Form", "Feature Extraction"))
        self.label_Method.setText(_translate("Form", "Method"))
        self.check_isWeighted.setText(_translate("Form", "Weighted"))
        self.label.setText(_translate("Form", "n_topics"))
        self.label_2.setText(_translate("Form", "ε"))
        self.label_3.setText(_translate("Form", "min"))
        self.radio_Embed.setText(_translate("Form", "Embedding"))
        self.radio_LDA.setText(_translate("Form", "LDA"))
        self.radio_DBSCAN.setText(_translate("Form", "DBSCAN"))
        self.radio_LOF.setText(_translate("Form", "LOF"))
        self.radio_IF.setText(_translate("Form", "Isolation Forest"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
